name: Sync Kindle Highlights
on: [push, workflow_dispatch]
jobs:
  sync-highlights:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @notionhq/client

      - name: Sync highlights
        run: node sync-highlights.js
        env:
          BOOK_DB_ID: ${{ vars.BOOK_DB_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

      - name: Commit cache changes
        uses: EndBug/add-and-commit@v7
        with:
          message: Commit cache changes
          add: sync.json

      - name: Push cache changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
